services:
  - type: web
    name: hlc-colour-match
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.app:app
    envVars:
      - key: PORT
        value: 10000
    autoDeploy: true