services:
  - type: web
    name: hlc-colour-connect
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.app:app"
    envVars:
      - key: PORT
        value: 10000